name: "tests"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  # Allow this workflow to be called from other workflows
  workflow_call:
    inputs:
      #  Requires at least one input to be valid, but in practice we don't need any
      dummy:
        type: string
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
          python-version: ${{ matrix.python-version }}
      - name: Cache Huggingface assets
        uses: actions/cache@v4
        with:
          key: huggingface-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          path: ~/.cache/huggingface
          restore-keys: |
            huggingface-${{ runner.os }}-${{ matrix.python-version }}-
      - name: Install dependencies
        run: pdm install
      - name: check formatting
        run: pdm run ruff format --check
      - name: check linting
        run: pdm run ruff check
      - name: check types
        run: pdm run pyright
      - name: test
        run: pdm run pytest